project_id = "mdwkkgancoocvkmecwkm"

[functions.ai-resource-discovery]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.coach-k]
verify_jwt = false

[functions.create-donation-payment]
verify_jwt = false

[functions.crisis-emergency-ai]
verify_jwt = false

[functions.crisis-support-ai]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.reentry-navigator-ai]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.send-partnership-email]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.victim-support-ai]
verify_jwt = false

[functions.ai-recommend-resources]
verify_jwt = false

[functions.partner-support-chat]
verify_jwt = false

[functions.generate-success-story]
verify_jwt = false

[functions.generate-marketing-image]
verify_jwt = false
